targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-musl",
]
ignore-dev-dependencies = true
accepted = [
    "Apache-2.0",
    "MIT",
    "MIT-0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]

[private]
ignore = true
